### ISSUE TITLE
defs >= &4000 at start results in no output

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/pyz80#13]
org 0
    dump 1,0
    defs &3fff
    defb 1

pyz80 --obj=space source.asm - results in the expected 16k object file.

    org 0
    dump 1,0
    defs &4000
    defb 1

pyz80 --obj=space source.asm - results in no object file at all.

**Comment by stefandrissen** [comment]
The use case for the above was to insert 16k to mdat "samdos" at 16384 because I was unable to get dZ80 to use an offset.

But I've found that the issue occurs when nothing has happened in a page yet. I'll create a PR.

**Comment by simonowen** [comment]
Fix merged, thanks!
