### ISSUE TITLE
if defined( symbol ) does not work due to whitespace

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/pyz80#14]
````
if defined(symbol) ; works
if defined( symbol) ; works
if defined( symbol ) ; does not work
````
The regexp on line 442 is incorrect, the ``(.*)`` is gobbling the trailing space and adding it to the symbol, resulting in the symbol not being found.

````
match = re.search('defined\s*\(\s*(.*)\s*\)', arg, re.IGNORECASE)
````

**Comment by simonowen** [comment]
Interesting find!  Changing the `.*` to `.*?` should hopefully fix it, if the re module support that syntax for non-greedy matching.

**Comment by stefandrissen** [comment]
Fix works! B

oth [Python 2](https://docs.python.org/2/library/re.html) and [Python 3](https://docs.python.org/3/library/re.html) documentation contain an example with non-greedy matching.

**Comment by simonowen** [comment]
Thanks for confirming.  I've cherry-picked your commit with a small edit as it conflicted with the raw string change in 28bfde2f04e234cefc2b1ca0f46eb478.

**Comment by stefandrissen** [comment]
Thanks - I'm pretty clueless on git commits - I'll see if I can rebase or so.
