### ISSUE TITLE
Invalid binary value silently resolves to 0

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/pyz80#16]
While making my mind up between using a hex or binary representation to mask off the lower four bits I ended up with:

    and %0f

And then spent quite some time scratching my head as to why the sambus real time clock was always returning 00:00.

The invalid binary value ``%0f`` is silently assembled to ``0``.

**Comment by simonowen** [comment]
Fixed in 4c6363ed014e400f1f7ed7ed0e0d1c9754c7c628.  Thanks for the report!
