### ISSUE TITLE
debugger / breakpoint

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/pyz80#19]
It would be useful to have a ``debugger`` or ``breakpoint`` expression that sets one (or multiple) breakpoint(s) for SimCoupe.

Work-arounds include:
- using the map file to set a breakpoint in SimCoupe 
- inserting ``di`` / ``halt``

**Comment by simonowen** [comment]
My only hesitation on adding them is whether they are too SimCoupe-specific to go in pyz80, and whether support could be improved on the SimCoupe side instead.

I quite often use the `DI;HALT` sequence as a breakpoint in code, then use the SimCoupe debugger to Ctrl-Down over the `HALT` or use `poke pc-1,0,0` to patch them out of commonly called code. I also have a common pattern where I eject and reinsert a modified disk image to update it. Both are just work-arounds I've got used to, but should probably be solved another way.

SimCoupe breakpoints could be persist across restarts and restored using the original symbol names to pick up new code locations. Modified disk images (and associated symbols) could be reloaded automatically when changed by an external program, to avoid the need to manually re-insert. Having a command-line option to pass media arguments to any existing SimCoupe instance would help preserve the debugging environment too.

Allowing some of the unused Z80 instructions might be another way to embed extra debug functionality. There are plenty free in the ED extended set, and some of the useless `LD r,r` could be repurposed too. They would be disabled by default in SimCoupe and behave as NOPs in any environment that doesn't know about them. As well as breakpoints these could mapped to other debug helpers, such as code profiling and realtime visual aids. If they were used via macros pyz80 wouldn't even need to know about them.

I'm sure the requirements are probably specific to the work-flow each person uses during development. I think the ideas above may cover the issues I usually work around. What about you?

**Comment by stefandrissen** [comment]
Yes, I thought a pyz80 / SimCoupe combo was required, but you are correct that really only SimCoupe needs some help.

I am hesitant with using adjusted code as a breakpoint (``di halt`` and unused instructions) since the code I am then debugging is not the code I will eventually be using.

Persistent breakpoints could be quite a nice addition (to SimCoupe).

But now that I've thought about it a bit longer, wouldn't the easiest, clearest and most clutter free approach be to just let SimCoupe auto-breakpoint on all symbols starting with ``(@)breakpoint``? 

Note that I am just using simple memory execution breakpoints. Possibly some sort of syntax could be used in the symbol like ``(@)breakpoint.read.1`` to indicate this address being read.

**Comment by stripwax** [comment]
I like the "annotated symbol" idea but it requires naming and renaming
symbols. So maybe just support a supplemental file / reference, passed to
simcoupe on command line, naming which symbols to add as breakpoints. E.g.
something you write in a text editor.  Generalising this, you could just
script other commands for simcoupe (e.g watch,  conditional breakpoints)
that way.

**Comment by simonowen** [comment]
I like the symbol idea for metadata too. I don't think it should require any renaming, just adding another symbol at the same code position if one already exists. Both symbols will map to the same address, and SimCoupe will just need to recognise the special symbols and send them to the debugger (as well as not using those names for address-to-symbol mapping).

Longer term I'd like Python bindings to be able to control the emulator (including the debugger), which would give much more flexibility for both developers and unit testing.

**Comment by simonowen** [comment]
I'll close up this pyz80 issue but I've added a SimCoupe ToDo item to experiment with using symbols to set breakpoints. I'm hoping it'll be simple enough to include ahead of something more comprehensive.
