### ISSUE TITLE
-I fails when import file is smaller than 501 bytes

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/pyz80#2]
When a file is imported that is smaller than 501 a corrupt disk image is created.

old code:

        if start_of_file:
            copylen = 501
            imagepos += 9
            start_of_file = False
        else:

new code:

        if start_of_file:
            if filelength > 500:
                copylen = 501
            else:
                copylen = filelength
            imagepos += 9
            start_of_file = False
        else:

**Comment by simonowen** [comment]
Thanks!
