### ISSUE TITLE
Index register offset check incorrect

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/pyz80#22]
The following source:
````
    ld a,(ix+256)
    ld a,(ix+128)
````
Will trigger ``warning: Unsigned byte value truncated from 256`` but will **not** trigger a warning for the second opcode, which becomes:

````
    ld a,(ix-128)
````
The index register offsets should be checked as being valid **signed** 8 bit values.

**Comment by simonowen** [comment]
Ouch -- I hope you didn't find that the hard way when it generated bad code!  I'm surprised it's gone unnoticed for so long.

**Comment by stefandrissen** [comment]
> Ouch -- I hope you didn't find that the hard way when it generated bad code! I'm surprised it's gone unnoticed for so long.

I had some messy code which I thought would clean up nicely with ``ix``, which I used to avoid like the plague for it's performance, but had completely overlooked the range and happily plugged in symbols that I knew had a +245 offset.

I think the Z80 craftmanship is fading :-)

**Comment by simonowen** [comment]
It looks like the range value checking is broken too, which was caught by the unit testing -- I'll have to look at tomorrow. It's using chained operators, which have an implicit `and` between them. That works well for checking in-range but not the out-of-range test used here.

**Comment by simonowen** [comment]
This was a little more complicated than I first thought but should be sorted now!

**Comment by stefandrissen** [comment]
This is throwing a few too many warnings IMHO:

````
defb -1

warning: Unsigned byte value truncated from -1
````
Along with any other attempt to use a negative number in any constant.

Also for 16 bit integers:

````
warning: Unsigned word value truncated from -11853

ld hl,- ( "M" + "." * 0x100 ) 
````

**Comment by simonowen** [comment]
The code is now doing what it was originally attempting, though it probably wouldn't have been left like that if it was working and they were visible! All the warnings are technically correct since their values don't fit without modification, but assemblers are usually a bit more relaxed about the values they accept.

Should all values be silently wrapped/truncated by default? Should warnings only be shown for positive overflow like before?

Bit position numbers and index register offsets are some cases where you'd always want to enforce it, of course. There could be a command-line option that enabled the strict range warnings in other contexts, for code that wants to know when adjustments are being made.

**Comment by stefandrissen** [comment]
Just thinking out loud:
- a byte can be signed -0x80 ... 0x7f **or** unsigned 0x00 ... 0xff;
- a word can be signed -0x8000 ... 0x7ff **or** unsigned 0x0000 ... 0xffff;
- an index register offset is **always** signed -0x80 ... 0x7f
- a bit position is always 0x00 ... 0x07

In the '**or**' cases, the assembler does not know if the value is intended to be signed or not, so anything in the range -0x80 ... 0xff or -0x8000 ... 0xffff is valid and should not lead to truncation.

**Comment by simonowen** [comment]
That's a good way of looking at it! It gives the flexibility to do what most users will expect, with warnings only when things go too far out of range. I'll see what I can come up with...

**Comment by simonowen** [comment]
Hopefully the new changes silence the warnings you were seeing, while keeping the original index offset fix. I'll leave this open until you're happy with it.

**Comment by stefandrissen** [comment]
"All" my projects assembly without warnings - so thanks for the quick fix!
